name: iOS Build

on:
  push:
    branches: [ main, copilot/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Build iOS app
      run: |
        cd iOS
        xcodebuild -project HelloWorld.xcodeproj \
          -scheme HelloWorld \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -configuration Debug \
          build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Build success
      run: echo "iOS build completed successfully!"
