name: iOS Build

on:
  push:
    branches: [ main, copilot/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build shared Swift package
      run: |
        swift build
        ./.build/debug/HelloWorld
    
    - name: Build iOS package
      run: |
        cd iOS
        swift build
    
    - name: Build for iOS Simulator (if xcodebuild available)
      continue-on-error: true
      run: |
        cd iOS
        # Note: This would require a proper Xcode project/workspace
        # For now, we just verify the package builds
        swift package resolve
        
    - name: Archive build artifacts
      if: success()
      run: |
        mkdir -p artifacts
        cp ./.build/debug/HelloWorld artifacts/
        tar -czf ios-build.tar.gz artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios-build.tar.gz
        retention-days: 7
